export enum CityTypes {
    ADD_CITY_REQUEST = 'city/ADD_CITY_REQUEST',
    ADD_CITY_SUCCESS = 'city/ADD_CITY_SUCCESS',
    GET_CITY_REQUEST = 'city/GET_CITY_REQUEST',
    GET_CITY_SUCCESS = 'city/GET_CITY_SUCCESS',
    REMOVE_CITY_REQUEST = 'city/REMOVE_CITY_REQUEST',
    ADD_FAVORITE_CITY = 'city/ADD_FAVORITE_CITY',
}